gpac/mp4box.js

- src/isofile.js
Backported from codem-isoboxer (with a small tweak to return early whenever a single box is found). Hope you find it useful.
> Fix for #50 (getBox/getBoxes)

- test/qunit-media-data.js
I added new mp4 test files with negative CTS-DTS offsets and with no default flags in fragments.
> Added new tests

- src/parsing/sampleentries/sampleentry.js
- src/writing/sampleentry.js
> Fix #137 - read and write compressorname correctly

- README.md
Some trivial typo fixes in README.md
> Trivial typo fixes in README.md

- src/box-codecs.js
- src/parsing/sampleentries/sampleentry.js
VP8 and VP9 samples can be parsed with this change.
> Add basic support for reading VPx in MP4

- src/box-codecs.js
- src/parsing/sampleentries/sampleentry.js
- src/parsing/vvcC.js
- src/parsing/vvnC.js
I primarily implemented parsing of the VvcDecoderConfigurationRecord and VvcPTLRecord in the vvcC box. Other features, like for example the VVC specific sample groups, are not implemented, yet.
> Add basic support for reading VVC im MP4

- src/isofile-advanced-creation.js
- src/writing/hvcC.js
Add the hvcC box writer for hevc stream muxing.
> Add hvcC box writer.

- src/box.js
- src/parsing/tyco.js
See ISO/IEC 14496-12:2022 Section 4.4 for etyp and tyco boxes
See https://github.com/nokiatech/heif_conformance/raw/master/conformance_files/C044.heic for a sample file
> etyp: implement extended type parsing

- src/parsing/udes.js
This is from ISO/IEC 23008-12:2022 Section 6.5.20.
> udes: initial implementation of UserDescriptionProperty

- src/parsing/mskC.js
See ISO/IEC 23008-12:2022 Section 6.10.2.2 Mask configuration item property
> mskC: add mask configuration item parsing

- src/parsing/sbpm.js
This is from the 23001-17 DIS Section 6.1.7.
I don't know of any public sample data, but I tested with one created with the gpac uncvg tool.
> add support for sensor bad pixel map (sbpm) box

- test/filereader.js
> load the URL given on the search parameters

- src/descriptor.js
- fix streamType property was parsed incorrectly.
- add upStream property
> DecoderConfigDescriptor:

- src/parsing/cmpd.js
- src/parsing/uncC.js
A couple of minor box definition updates to reflect changes in 23001-17 FDIS
> uncompressed: update to FDIS box configuration

- src/parsing/EntityToGroup.js
Add the Image Pyramid Entity group.
> Add pymd box

- src/parsing/lhvC.js
Defined in clause 9.4.3 of ISO/IEC 14496-15:2022
> add support for lhvC box

- src/parsing/uncC.js
> display uncC profile as string

- src/parsing/lhvC.js
Based on code from d1cb88f042ab7b6fbf931cf2b027e81e558af26b.
> Format SPS and PPS in avcC and nalu_arrays in lhvc in string format

- src/box-diff.js
there are two sample_counts in BoxParser.DIFF_PRIMITIVE_ARRAY_PROP_NAMES
> Update box-diff.js, remove duplicate item

- test/filereader.html
- test/filereader.js
For convenience.
It looks like that on my browser:
> Add ExpandAll and CollapseAll buttons

- demo/boxHtmlTable.js
- src/boxes/avcC.ts
Fixes a missing display for SPS and PPS values
> Improve avcC BoxProperty display
