gpac/mp4box.js

src/mp4box.js

If the first track doesn't have enough data, the function returns and all other tracks cannot be processed.
It should be break instead.

Fixed bug that extracting multiple tracks at the same time can fails

---

src/box.js
src/parsing/dfLa.js
test/sample-urls.js

Adds basic support for parsing fLaC sample entry as requested in https://github.com/gpac/mp4box.js/issues/128, and as defined in https://github.com/xiph/flac/blob/master/doc/isoflac.txt.
The dfLa box is read and the samplerate extracted from the STREAMINFO block, if present. All other fields in STREAMINFO are ignored. Non-STREAMINFO blocks are not parsed, although the total number of blocks and their types presence is noted.

Add support for parsing FLAC in ISOBMFF

---

src/parsing/sidx.js

Found that the sidx `first_offset` was consistently off by the stream position, so I append this value to the final value to produce a correct offset.

Ensure that sidx first offset is complete

---

src/isofile.js

When seeking a video file that has been completely downloaded and
appended, you will constantly encounter a seekTrack error because it
does not bail checking for new samples.
Fixes: #99, #125

Fixes constant seeking error

---

src/writing/avcC.js

Due to the refactor putting the buffer data in the `nalu` prop, this
fixes the writing.
Reference: https://github.com/gpac/mp4box.js/issues/154
Closes: #154 and #166

Corrects the writing of avcC data

---

src/box.js
src/parsing/uuid/piff/piffLsm.js
src/parsing/uuid/piff/piffTfrf.js
src/parsing/uuid/piff/piffTfxd.js

Decode a couple of Smooth Streaming boxes. This requires enabling UUID parsing, which was commented out for some reason.

Add MSS LiveStreamManifest, Tfrf Tfxd UUID box parsing

---

src/isofile.js

According to ISO/IEC 14496-12, creation_time is an integer that declares the creation time of the presentation (in seconds since midnight, Jan. 1, 1904, in UTC time).
var _1904 should also be in UTC time, while new Date(4, 0, 1, 0, 0, 0, 0).getTime() returns Jan. 1, 1904, in local time.

fixes invalid created, modified date

---

.travis.yml
karma.conf.js
package.json

This makes it possible to build mp4box without installing global
dependencies:
npm install
./node_modules/.bin/grunt
EDIT: I merged #149 into this to demonstrate that the tests still pass.

Add grunt-cli to devDependencies

---

.travis.yml
karma.conf.js

I'm hoping this will make Travis more useful for pull requests.
EDIT: It looks like the tests passed, but the build stalled:
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
> 
> The build has been terminated

Don't require $NPM_TOKEN for Travis tests, only deployment

---

.travis.yml
karma.conf.js
src/log.js

This fixes the following error when running `test/node/info.js`:
TypeError: output.log is not a function
at BoxParser.Box.printHeader (/home/josephfrazier/workspace/mp4box.js/dist/mp4box.all.js:7436:9)
at BoxParser.Box.print (/home/josephfrazier/workspace/mp4box.js/dist/mp4box.all.js:7448:7)
at ISOFile.print (/home/josephfrazier/workspace/mp4box.js/dist/mp4box.all.js:7467:18)
at Object.<anonymous> (/home/josephfrazier/workspace/mp4box.js/test/node/info.js:10:25)
at Module._compile (internal/modules/cjs/loader.js:678:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
at Module.load (internal/modules/cjs/loader.js:589:32)
at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
at Function.Module._load (internal/modules/cjs/loader.js:520:3)
at …

Add `.log` method to Log object

---

src/isofile-sample-processing.js
src/parsing/sampleentries/sampleentry.js

Fixes: throwing errors reporting that these two variables are not declared.

Add in missing variable declarations for compressorname_length and trak

---

src/isofile-advanced-creation.js
src/isofile-write.js

`sequence_number` is generated incorrectly because context is lost

fix mfhd box sequence_number

---

test/filereader.js

Enable filereader to complete when segment does not include sidx box - check there is a sensible sidx and return early if not rather than blindly carrying on.
See #254 for further discussion

Fix #254 - guard against undefined or incomplete sidx when building UI

---

src/isofile.js

Without this mp4box.js cannot be used when "strict" mode is enabled.

declare ref variable in getInfo

---

src/isofile-advanced-creation.js

first_dts setted as the first > 0 number instead of the real first one.
and that will make the video has the head 2 frames start from 0 timestamp.

bugfix: set first_dts

---

src/isofile-write.js
src/isofile.js

I found a problem with sample extraction: `nextSeekPosition` was never updated when samples were missing from buffers. This causes `onSamples` to not be called if the data is not already in the buffers as `appendBuffer` would never return the offset required for the sample extraction track.
I tried to fix it with this change, feel free to make changes / suggest a better solution.

fix: set next seek position if sample data is missing for extracted tracks samples

---

src/isofile.js

Fix issue with files that have some tracks that don't extend the whole duration of the video. `ISOFile.prototype.seek` would return the offset based on already ended tracks and thus cause unnecessary downloads/buffering. Tried to explain behaviour below:
Before:
```
Video track 1: ====================================
Audio track 1: ====================================
Audio track 2: ===========
^                  ^
returned offset           seek
```
After:
```
Video track 1: ====================================
Audio track 1: ====================================
Audio track 2: ===========
^
seek & returned offset
```

fix(ISOFile.prototype.seek): skip already ended tracks

---

src/box.js
src/parsing/EntityToGroup.js

Add group list (`grpl`) per ISO/IEC 14496-12:2022 section 8.18.2, and various entity to group boxes (as noted in in-code comments).
Samples at https://github.com/nokiatech/heif/raw/gh-pages/content/heifv2/bothie_1440x960.heic and https://github.com/nokiatech/heif/raw/gh-pages/content/heifv2/stereo_1200x800.heic for a couple of grouping types.

implement entity to group boxes

---

src/parsing/ccst.js

See ISO/IEC 23008-12:2022 Section 7.2.3
For a sample that uses this, see https://github.com/nokiatech/heif_conformance/raw/master/conformance_files/C038.heic

ccst: parse out coding contraint box

---

src/parsing/singleitemtypereference.js
src/parsing/singleitemtypereferencelarge.js

This enables the `to_item_ID` from SingleItemReferenceBox and SingleItemReferenceBoxLarge to be displayed in the box view (rather than just a leaf node).
Example that shows this: https://github.com/nokiatech/heif_conformance/raw/master/conformance_files/C005.heic (on the `thmb` .
Before:
After:

iref: show to_item_ID value

---

src/box.js
src/parsing/cdef.js

The '_j2kH_' box:
- is named the J2KHeaderItemProperty or J2KHeaderInfo box. 
- is a superbox, which means that it only contains other boxes
- is defined in ISO/IEC 15444-16
- is used to store JPEG 2000 metadata
The '_cdef_' box:
- is named the Channel Definition box.
- is defined in ISO/IEC 15444-1.
- shall be present in the j2kH box.
- Provides channel information. (RGB, Grayscale, YCC, etc.)

Add j2kH & cdef Box definitions

---

src/isofile-item-processing.js
test/filereader.html
test/filereader.js

Prior to this change,  property processing will throw if the association is not found in the item list. That can happen because the association is broken, and can also happen on a valid file if the property is associated with a group rather than a single item. 
This change links the property to either the item or the group, and protects against the case where the association is not valid against either.
It also adds display of groups (including entity IDs, and properties) to the filereader UI.
(This shows a slightly different styling - `th` is `text-align: left;` instead of `text-align: center;` - happy to propose that as a follow-up change if desired).
For an example that shows the problem (and displays in the new UI), see https://github.com/nokiatech/heif_conformance/raw/master/conforman …

improve group and property handling

---

src/parsing/iloc.js

When the iloc box version is 2, the item_ID should be a parsed as a 32 bit unsigned integer, not 16.

iloc version bug

---

src/parsing/cmpd.js

The previous update for FDIS compatibility was wrong for this box.
The size of the component should have been unchanged. Only the component count should be 32 bits.
Thanks to @dukesook and @EnvitiaAlexScottJohns for the diagnosis.

cmpd: fix parsing

---

README.md

updated README.md to fix a variable naming inconsistency mistake in mp4boxfile initialization. The mistake is in the code for the Segmentation example. 
should be:
``` js
var mp4boxfile = MP4Box.createFile();
mp4boxfile.onReady = function(info) {
...
};
```
not:
``` js
var mp4box = MP4Box.createFile();
mp4boxfile.onReady = function(info) {
...
};
```
Renamed the variable `mp4box` to `mp4boxfile` for consistency throughout the codebase.

doc: Fix variable naming inconsistency in MP4Box initialization

---

src/parsing/dfLa.js
src/parsing/sampleentries/sampleentry.js

Original Flac parsing implementation from https://github.com/gpac/mp4box.js/pull/134, was broken due to prior refactoring. This pull request restores functionality by adding back the `fLaC` box to the sample entry list, and removing the extra header parse call in `dfLa.js`

Fix parsing Flac boxes

---

src/writing/hvcC.js

Current code:
```js
stream.writeUint8(this.general_profile_space << 6 +
this.general_tier_flag << 5 +
this.general_profile_idc);
```
is equivalent to 
```js
stream.writeUint8(this.general_profile_space << (6 +
this.general_tier_flag) << (5 +
this.general_profile_idc));
```
which is incorrect. The correct order of operations are:
```js
stream.writeUint8((this.general_profile_space << 6) +
(this.general_tier_flag << 5) +
this.general_profile_idc);
```
This fixes the file segmenter tool producing invalid hvcC boxes for certain kinds of hvc1 video.

Fix hvcC box writing using incorrect order of operations

---

src/parsing/saiz.js

This is useful when the `default_sample_info_size` is used and there are no entries in the `sample_info_size` array.
Resolves #390.

saiz: add sample_count to box structure

---

src/isofile-item-processing.js

This means offset from the start of the iloc box content, and is implemented by adjusting the flattened offsets to match.
Thanks to @NuriaJulia for identifying the issue and the analysis.

add support for iloc construction method 1

---

src/parsing/saio.js
src/parsing/saiz.js

Currently, MP4Box.js displays the aux_info_type parameter in the saiz/saio boxes as a decimal value (e.g. **1635017065)**. Displaying this value as a string would be much more convenient (e.g. **'atai'**).
</body>
</html>

Parse aux_info_type as string

---

src/isofile-item-processing.js
src/isofile.js

Every instances of `ISOFile` are sharing same `items`, `entity_groups` list.

Fix problem that every instance shares same items list

---

src/descriptor.js

Resolved a logic error occurring when the size exceeds 2 bytes. Please, refer to the [Chromium source code](https://chromium.googlesource.com/chromium/src/media/+/16ba1c56b860d53d7354c0ec9538650cf1f20e2d/mp4/es_descriptor.cc#21)

Fixed ESDS size parsing

---

test/qunit-helper.js

see https://github.com/gpac/mp4box.js/issues/357#issuecomment-2609298718
Since I'm not a regular contributor to mp4box.js I'm doing this as a PR in case there are some objections to doing changing this.

get conformance tests from telecom server (#357)

---

src/box.js

This was accidentally broken in #438 and it prevents loading fragmented mp4 since the trexs property does not exist anymore in `ISOFile.getTrexById`

Fix mvex child box name to be trex

---

src/box.js
src/parsing/uuid/piff/piffLsm.js
src/parsing/uuid/piff/piffPssh.js
src/parsing/uuid/piff/piffSenc.js
src/parsing/uuid/piff/piffTenc.js
src/parsing/uuid/piff/piffTfrf.js
src/parsing/uuid/piff/piffTfxd.js

Add friendly names to PIFF/Smooth boxes.
Looks like the call to `FullBox` was incorrect after #438 so add `name` to constructor call.

Fix and name PIFF/Smooth UUID boxes

---

src/parsing/av1C.js

I'm not a 100% familiar with AV1 but I think this is how it is supposed to be fixed.
`(tmp >> 7) & 0x1 !== 1`
First of all this is wrong, `0x1 !== 1` has a priority over the `&` so this is always false and the error never occurs. I think here we are checking the forbidden bit which is the first bit of the byte and must always be 0. So we need `(byte >> 7 & 1) !== 0` to trigger the error (or perhaps `== 1`)

Fix forbidden bit check in av1C parsing

---

test/ui-helper.js

Show the box's index instead of "undefined" (regression from commit 92eb110).

Handle boxes with no type.

---

src/box.js

`!mov` and `!mof` are compressed `moov` and `moof` boxes.

Fix moov and moof box names

---

src/parsing/uuid/gimi/gimiItemContentID.js

The `ItemContentIDProperty` UUID box is defined in the GIMI profile (see NGA.STND.0076 v1.0).
```C++
aligned(8) class ItemContentIDProperty
extends ItemProperty('uuid',0x261ef3741d975bbaacbd9d2c8ea73522) {
utf8string ItemContentID;
}
```

GIMI: uuid ItemContentID

---

src/boxes/sampleentries/base.ts

fix: add missing VisualSampleEntry's box types

---

entries/all-boxes.ts
src/boxes/defaults.ts
src/boxes/prfr.ts

`prfr` is the OMAF ProjectionFormatBox, which is nested within the `povd` container. See ISO/IEC 23090-2:2023 Section 7.6.2.2 for both.
There is an image property for `prfr`, which is the same syntax, but is nested within `ipco` instead. See ISO/IEC 23090-2:2023 Section 7.9.3.2.

feat: add prfr box and povd container

---

src/boxes/sampleentries/sampleentry.ts

Adds display names for sample entries.
I use mp4box.js to display the file structure - https://gpac.github.io/mp4box.js/test/filereader.html or a local instance.
The box tree has names for most things, but not for sample entries. An example is shown below:
AFAICT, there are not really "box names" for these SampleEntry instances, but there is a reasonable description on the MP4RA web site - https://mp4ra.org/registered-types/codecs
Some of those aren't great, but I tried to keep close to the terms used there, especially for codecs that aren't very common.

fix: add box(-like) names for sample entries

---

src/box.ts
src/boxes/elst.ts
src/boxes/mdhd.ts
src/boxes/mehd.ts
src/boxes/mvhd.ts
src/boxes/sidx.ts
src/boxes/tfdt.ts
src/boxes/tkhd.ts
src/constants.ts

Consider the following test. It will fail because there is an off-by-one error in the calculation of the field size needed to store baseMediaDecodeTime. There are a bunch of these, including in the base Box size calculation. Seems to have been introduced in the TS rewrite.
```
describe('tfdtBox', () => {
it('writes a version 1 box when presented with a baseMediaDecodeTime > 32 bits', () => {
const smallest_thirtythree_bit_number = Math.pow(2, 32);
const tfdt = new tfdtBox();
tfdt.baseMediaDecodeTime = smallest_thirtythree_bit_number;
const stream = new MultiBufferStream();
tfdt.write(stream);
const expected = new Uint8Array([
0x00, 0x00, 0x00, 0x14, // size (20 bytes)
0x74, 0x66, 0x64, 0x74, // type 'tfdt'
0x01,                   // version 1
0x00, 0x00, 0x00,       // flags
0x00, 0x00, …
```

fix: off by one errors in box and field size calculations
